### ISSUE TITLE
17 virus on this file exe

### ISSUE THREAD

**Issue by sealabr** [Ascerr/Rifbot#1]
Here's the analyze:

https://www.virustotal.com/gui/file/81c5c10b83667263d6f16431635bfe6b98da8866a768bfae093cd874361fafdc/detection

**Comment by Ascerr** [comment]
Hello,

It's bot mate, for antyvirus there is no difference between virus and
bot. Additional it's AutoIt language so online scaners hate it ;D

2021-02-14 21:14 GMT+01:00, Fábio Mendes Viana <notifications@github.com>:

**Comment by sealabr** [comment]
thanks for the fast reply, do you have the source code for exe file? thanks

**Comment by Ascerr** [comment]
Of course i had but it's required to compile exe.

2021-02-14 22:36 GMT+01:00, Fábio Mendes Viana <notifications@github.com>:

**Comment by sealabr** [comment]
no prob, i can compile here

**Comment by Ascerr** [comment]
Are you joking XD

It's paid software ;D

2021-02-15 18:13 GMT+01:00, Fábio Mendes Viana <notifications@github.com>:
